name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ou a versão que você precisa

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Build Docker Image
        run: |
          docker build -t dima-api:latest .

      - name: Login to Railway
        run: railway login
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: |
          railway up --service dima-api --image dima-api:latest
